### ISSUE TITLE
Totaltext复现结果问题

### ISSUE THREAD

**Issue by 123cjjjj** [GXYM/TextBPN-Plus-Plus#12]
谢谢作者对论文代码的开源，利用作者开源的基于Totaltext训练的模型进行测试，发现得到的结果达不到论文中公布的指标，评估出得到的结果是针对两种不同的tr和tp情况得到对应的F值，请问论文中给出的针对这个数据集的结果是在哪个tr和tp下得到的，对tr和tp以及F值的关系不太清楚，望回复！谢谢~

**Comment by GXYM** [comment]
> 谢谢作者对论文代码的开源，利用作者开源的基于Totaltext训练的模型进行测试，发现得到的结果达不到论文中公布的指标，评估出得到的结果是针对两种不同的tr和tp情况得到对应的F值，请问论文中给出的针对这个数据集的结果是在哪个tr和tp下得到的，对tr和tp以及F值的关系不太清楚，望回复！谢谢~

利用我们开源的模型测试，达不到公布的指标？差多少？你使用了我们提供的官方的评测代码？如果只差了一点点，这没有必要计较吧，不同的显卡会有一点点差别，因为计算精度不一样

**Comment by GXYM** [comment]
> 谢谢作者对论文代码的开源，利用作者开源的基于Totaltext训练的模型进行测试，发现得到的结果达不到论文中公布的指标，评估出得到的结果是针对两种不同的tr和tp情况得到对应的F值，请问论文中给出的针对这个数据集的结果是在哪个tr和tp下得到的，对tr和tp以及F值的关系不太清楚，望回复！谢谢~

“请问论文中给出的针对这个数据集的结果是在哪个tr和tp下得到的，对tr和tp以及F值的关系不太清楚” 我们已经在代码中集成了测试代码，测试完成，测试结果会自动打印，对应的tr和tp也有。对于评测方法有疑问，请参考官方的评测方法的介绍。

**Comment by GXYM** [comment]
> 出得到的结果是

我们报告的结果，对应的是tr=0.7和tp=0.6的结果，官方提倡使用这组参数评测

**Comment by GXYM** [comment]
> 谢谢作者对论文代码的开源，利用作者开源的基于Totaltext训练的模型进行测试，发现得到的结果达不到论文中公布的指标，评估出得到的结果是针对两种不同的tr和tp情况得到对应的F值，请问论文中给出的针对这个数据集的结果是在哪个tr和tp下得到的，对tr和tp以及F值的关系不太清楚，望回复！谢谢~

我们报告的结果，对应的是tr=0.7和tp=0.6的结果，官方提倡使用这组参数评测

**Comment by GXYM** [comment]
其他的，我没有什么可以提供给你的帮助。如果后期有其他人再反映用我们提供的模型测试，达不到论文中的效果（微小误差除外），那我们在我们这边在检查我们的模型和代码。但现在提供的模型和代码应该是没啥问题的，因为有人测试说提供的模型测试结果和论文的差别很微小，针对他的问题我们已经修复了训练代码的bugs.每个问题都要我们，检查一遍太耗时了，所以我们会针对反映多的问题和比较重要的问题，进行检查和修复。请谅解，谢谢！
