### ISSUE TITLE
请问Totaltext数据集哪个版本比较好呢

### ISSUE THREAD

**Issue by 921162820** [GXYM/TextBPN-Plus-Plus#15]
想复现一下，不知道是新版本标注更好呢还是老版本的更好呢

**Comment by GXYM** [comment]
我们使用的是老版本的total_text,据说新版的total-text数据集标注更合理，歧义标注更少。我们没有仔细对比过两者的差距，不过新版本的total-text数据集的加载脚本，我们的代码里也提供了。发自我的荣耀手机-------- 原始邮件 --------发件人： 921162820 ***@***.***>日期： 2023年1月17日周二 01:27收件人： GXYM/TextBPN-Plus-Plus ***@***.***>抄送： Subscribed ***@***.***>主    题： [GXYM/TextBPN-Plus-Plus] 请问Totaltext数据集哪个版本比较好呢 (Issue #15)

想复现一下，不知道是新版本标注更好呢还是老版本的更好呢

**Comment by 921162820** [comment]
感谢作者的回复，再请问您一个问题，就是ctw1500数据集您试过新版的么，要是没有那我之后还用旧版的

**Comment by GXYM** [comment]
我们用的是旧版本的ctw1500。新版本的ctw1500,训练集标注确实规范了很多，但是测试集没什么变化，只是把中文变成了don't care。所以测试集还是存在很多歧义标注，这样我认为测试集和训练集标注差别更大了，不确定删除中文会带来多大的影响。不过新旧版本，性能应该差的不会特别多。建议先使用旧版本的，好和其他方法对比，然后在尝试新版本的。发自我的荣耀手机-------- 原始邮件 --------发件人： 921162820 ***@***.***>日期： 2023年1月17日周二 09:39收件人： GXYM/TextBPN-Plus-Plus ***@***.***>抄送： "S.X.Zhang" ***@***.***>, Comment ***@***.***>主    题： Re: [GXYM/TextBPN-Plus-Plus] 请问Totaltext数据集哪个版本比较好呢 (Issue #15)

感谢作者的回复，再请问您一个问题，就是ctw1500数据集您试过新版的么，要是没有那我之后还用旧版的

**Comment by 921162820** [comment]
非常感谢，我没问题了
