### ISSUE TITLE
About the training time

### ISSUE THREAD

**Issue by lcy0604** [GXYM/TextBPN-Plus-Plus#16]
Thanks for your excellent work. I have trained your TextBPN++ on my scene text dataset with a single 3090, but I found the training  time is too long. Our data is about 9000 and the batch size is set to 8. I adjust the input size to 800. How much time do you spend on training?

**Comment by GXYM** [comment]
> Thanks for your excellent work. I have trained your TextBPN++ on my scene text dataset with a single 3090, but I found the training time is too long. Our data is about 9000 and the batch size is set to 8. I adjust the input size to 800. How much time do you spend on training?

In training, I set the the input size to 640 with batch size is set to 12， which can make training time is shorter. But in this way, it also takes about a week of training on MLT17 (9000 imgs) with a single 3090. The training time is mainly limited by the computing ability of the CPU, because of the data augmentation algorithm. Therefore, it is recommended to use stronger cups and as many threads as possible, as memory allows.

**Comment by lcy0604** [comment]
> > Thanks for your excellent work. I have trained your TextBPN++ on my scene text dataset with a single 3090, but I found the training time is too long. Our data is about 9000 and the batch size is set to 8. I adjust the input size to 800. How much time do you spend on training?
> 
> In training, I set the the input size to 640 with batch size is set to 12， which can make training time is shorter. But in this way, it also takes about a week of training on MLT17 (9000 imgs) with a single 3090. The training time is mainly limited by the computing ability of the CPU, because of the data augmentation algorithm. Therefore, it is recommended to use stronger cups and as many threads as possible, as memory allows.

Thank you for your reply

**Comment by 123cjjjj** [comment]
> > > Thanks for your excellent work. I have trained your TextBPN++ on my scene text dataset with a single 3090, but I found the training time is too long. Our data is about 9000 and the batch size is set to 8. I adjust the input size to 800. How much time do you spend on training?
> > 
> > 
> > In training, I set the the input size to 640 with batch size is set to 12， which can make training time is shorter. But in this way, it also takes about a week of training on MLT17 (9000 imgs) with a single 3090. The training time is mainly limited by the computing ability of the CPU, because of the data augmentation algorithm. Therefore, it is recommended to use stronger cups and as many threads as possible, as memory allows.
> 
> Thank you for your reply

您好，3090环境下需要修改项目中的哪些参数啊？与3080环境训练的结果相差较大
