### ISSUE TITLE
日志位置

### ISSUE THREAD

**Issue by jihuan1203** [GXYM/TextBPN-Plus-Plus#25]
你好，我想问一下，运行生成的日志保存在什么位置？
我在使用命令`python3 train_textBPN.py --exp_name Ctw1500 --net resnet50 --scale 1 --max_epoch 660 --batch_size 8 --gpu 1 --input_size 640 --optim Adam --lr 0.001 --num_workers 8`运行时，因为自身原因，训练中断，并且没有找到log.txt文件

**Comment by GXYM** [comment]
> 你好，我想问一下，运行生成的日志保存在什么位置？ 我在使用命令`python3 train_textBPN.py --exp_name Ctw1500 --net resnet50 --scale 1 --max_epoch 660 --batch_size 8 --gpu 1 --input_size 640 --optim Adam --lr 0.001 --num_workers 8`运行时，因为自身原因，训练中断，并且没有找到log.txt文件

这个代码没有保存日志文件，如果你想保存日志文件，请参考https://github.com/GXYM/DRRG/blob/master/train_TextGraph.py修改，或者使用nohup python your_script.py > your_log_file.log 2>&1 &在后台运行命令并保存输出到log

**Comment by jihuan1203** [comment]
好的谢谢
