### ISSUE TITLE
Pre-trained models unavailable

### ISSUE THREAD

**Issue by max-aamir** [GXYM/TextBPN-Plus-Plus#3]
Hello, I tried to download your pre-trained models from Google drive and Baidu but google drive shows "Access Denied" and baidu website is not reachable. How can I download your pre-trained models?

**Comment by GXYM** [comment]
> Hello, I tried to download your pre-trained models from Google drive and Baidu but google drive shows "Access Denied" and baidu website is not reachable. How can I download your pre-trained models?

I test my links after you opened this issue. It works. Sorry, I don't know why it's not accessible under your network.

**Comment by max-aamir** [comment]
May be you forgot to share the file to **everyone**. Please check. You can make sure of its access by opening the link of any pre-trained model in Incognito mode. Here is the link of one of the pre-trained model -
https://drive.google.com/file/d/11AtAA429JCha8AZLrp3xVURYZOcCC2s1/view?usp=sharing
this is the link shared by you as given on the ReadMe.MD file. Please open it using Incognito Mode of your browser.

**Comment by max-aamir** [comment]
Brother I am already signed in with my google account. I am sharing the screenshot of the webpage that is visible on my side when I tried to open the pre-trained model on TotalText Res50-1s-DCN.
![Screenshot (1063)](https://user-images.githubusercontent.com/64240775/173572541-b4f4fe2d-84a9-4040-83a5-3bdfa4032696.png)

**Comment by max-aamir** [comment]
Please look into the links once because they are not working if it were why I bother ?

**Comment by GXYM** [comment]
> Please look into the links once because they are not working if it were why I bother ?

 We have updated our links again. You can try to download  it again.
