### ISSUE TITLE
about missing single digit and sign

### ISSUE THREAD

**Issue by tairen99** [GXYM/TextBPN-Plus-Plus#35]
Thank you for your wonderful work!

I am trying to fine-tune your model to detect document text, but I notice there are some single digit and single sign, such as "-",  are missing. Do you know what would be the possible reason? or any place you have some preprocessing or postprocessing to remove small contour of texts?

I tried to reduce the "dis_threshold" but it does not help.
Thank you in advance!

![image](https://github.com/GXYM/TextBPN-Plus-Plus/assets/32938376/cb689fcb-863f-4513-91fd-981435707e9c)
![image](https://github.com/GXYM/TextBPN-Plus-Plus/assets/32938376/5aba630a-88f8-4b55-a778-b36ebb596496)

**Comment by GXYM** [comment]
> Thank you for your wonderful work!
> 
> I am trying to fine-tune your model to detect document text, but I notice there are some single digit and single sign, such as "-", are missing. Do you know what would be the possible reason? or any place you have some preprocessing or postprocessing to remove small contour of texts?
> 
> I tried to reduce the "dis_threshold" but it does not help. Thank you in advance!
> 
> ![image](https://private-user-images.githubusercontent.com/32938376/294058103-cb689fcb-863f-4513-91fd-981435707e9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzUxMzYsIm5iZiI6MTcwNDMzNDgzNiwicGF0aCI6Ii8zMjkzODM3Ni8yOTQwNTgxMDMtY2I2ODlmY2ItODYzZi00NTEzLTkxZmQtOTgxNDM1NzA3ZTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAyMjAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZmU4Y2ViYzUyNzA0NWI5MTkwMDBiZDgwMDc5ZWEwNThhNDI1N2QxN2IxZDg5MTY5ZTgyYzNjZGUwZDkwYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.231HvFqIG-X2Zf3_gcmaQ4FfGJQsrajfyYJxTWge0fw) ![image](https://private-user-images.githubusercontent.com/32938376/294058178-5aba630a-88f8-4b55-a778-b36ebb596496.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzUxMzYsIm5iZiI6MTcwNDMzNDgzNiwicGF0aCI6Ii8zMjkzODM3Ni8yOTQwNTgxNzgtNWFiYTYzMGEtODhmOC00YjU1LWE3NzgtYjM2ZWJiNTk2NDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAyMjAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZGM0ZDA5Y2U1NTU3MDhjMjQ4MzRlMjg3ZDE3NWQwN2I0OGY4ZjFhN2U4MGM4NGRhMDQ2YzBiYjRlODkzNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qbS3GkBgthJcPvBQDaStNF-U1NeQ3JhP6VnSkb32mWE)

When creating training data, small text is also removed by default.
https://github.com/GXYM/TextBPN-Plus-Plus/blob/277029349de264099f9cf13f218ed2e6a893be36/dataset/dataload.py#L178

**Comment by tairen99** [comment]
> > Thank you for your wonderful work!
> > I am trying to fine-tune your model to detect document text, but I notice there are some single digit and single sign, such as "-", are missing. Do you know what would be the possible reason? or any place you have some preprocessing or postprocessing to remove small contour of texts?
> > I tried to reduce the "dis_threshold" but it does not help. Thank you in advance!
> > ![image](https://private-user-images.githubusercontent.com/32938376/294058103-cb689fcb-863f-4513-91fd-981435707e9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzUxMzYsIm5iZiI6MTcwNDMzNDgzNiwicGF0aCI6Ii8zMjkzODM3Ni8yOTQwNTgxMDMtY2I2ODlmY2ItODYzZi00NTEzLTkxZmQtOTgxNDM1NzA3ZTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAyMjAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZmU4Y2ViYzUyNzA0NWI5MTkwMDBiZDgwMDc5ZWEwNThhNDI1N2QxN2IxZDg5MTY5ZTgyYzNjZGUwZDkwYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.231HvFqIG-X2Zf3_gcmaQ4FfGJQsrajfyYJxTWge0fw) ![image](https://private-user-images.githubusercontent.com/32938376/294058178-5aba630a-88f8-4b55-a778-b36ebb596496.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzUxMzYsIm5iZiI6MTcwNDMzNDgzNiwicGF0aCI6Ii8zMjkzODM3Ni8yOTQwNTgxNzgtNWFiYTYzMGEtODhmOC00YjU1LWE3NzgtYjM2ZWJiNTk2NDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAyMjAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZGM0ZDA5Y2U1NTU3MDhjMjQ4MzRlMjg3ZDE3NWQwN2I0OGY4ZjFhN2U4MGM4NGRhMDQ2YzBiYjRlODkzNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qbS3GkBgthJcPvBQDaStNF-U1NeQ3JhP6VnSkb32mWE)
> 
> When creating training data, small text is also removed by default.
> 
> https://github.com/GXYM/TextBPN-Plus-Plus/blob/277029349de264099f9cf13f218ed2e6a893be36/dataset/dataload.py#L178

Thanks a lot for your quick reply!


> > Thank you for your wonderful work!
> > I am trying to fine-tune your model to detect document text, but I notice there are some single digit and single sign, such as "-", are missing. Do you know what would be the possible reason? or any place you have some preprocessing or postprocessing to remove small contour of texts?
> > I tried to reduce the "dis_threshold" but it does not help. Thank you in advance!
> > ![image](https://private-user-images.githubusercontent.com/32938376/294058103-cb689fcb-863f-4513-91fd-981435707e9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzUxMzYsIm5iZiI6MTcwNDMzNDgzNiwicGF0aCI6Ii8zMjkzODM3Ni8yOTQwNTgxMDMtY2I2ODlmY2ItODYzZi00NTEzLTkxZmQtOTgxNDM1NzA3ZTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAyMjAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZmU4Y2ViYzUyNzA0NWI5MTkwMDBiZDgwMDc5ZWEwNThhNDI1N2QxN2IxZDg5MTY5ZTgyYzNjZGUwZDkwYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.231HvFqIG-X2Zf3_gcmaQ4FfGJQsrajfyYJxTWge0fw) ![image](https://private-user-images.githubusercontent.com/32938376/294058178-5aba630a-88f8-4b55-a778-b36ebb596496.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzUxMzYsIm5iZiI6MTcwNDMzNDgzNiwicGF0aCI6Ii8zMjkzODM3Ni8yOTQwNTgxNzgtNWFiYTYzMGEtODhmOC00YjU1LWE3NzgtYjM2ZWJiNTk2NDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAyMjAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZGM0ZDA5Y2U1NTU3MDhjMjQ4MzRlMjg3ZDE3NWQwN2I0OGY4ZjFhN2U4MGM4NGRhMDQ2YzBiYjRlODkzNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qbS3GkBgthJcPvBQDaStNF-U1NeQ3JhP6VnSkb32mWE)
> 
> When creating training data, small text is also removed by default.
> 
> https://github.com/GXYM/TextBPN-Plus-Plus/blob/277029349de264099f9cf13f218ed2e6a893be36/dataset/dataload.py#L178

Thank you very much for your quick reply.
Let me fine-tine it again and see how it goes.
Thank you for your suggestion!
