### ISSUE TITLE
使用Totaltext新版训练集的问题

### ISSUE THREAD

**Issue by lightchaser0** [GXYM/TextBPN-Plus-Plus#46]
因为想使用新版数据集训练，Train_textBPN.py文件修改如下
`trainset = TotalText_New( data_root='data/Total-Text', ignore_list=None, is_training=True, load_memory=cfg.load_memory, transform=Augmentation(size=cfg.input_size, mean=cfg.means, std=cfg.stds) )`
然后根据total-text下readme调整了数据集路径（Total-Text/gt/Polygon/Test,Total-Text/gt/Polygon/Train）
训练数据集使用的是最新的版本 (https://github.com/cs-chan/Total-Text-Dataset/tree/master/Groundtruth/Text该链接下提供Latest refined version版本)，没有修改其他位置的代码。
训练执行代码如下： `CUDA_LAUNCH_BLOCKING=1 python3 train_textBPN.py --exp_name Totaltext --net resnet50 --scale 1 --max_epoch 660 --batch_size 12 --gpu 0 --input_size 640 --optim Adam --lr 0.001 --num_workers 20 --viz --viz_freq 80`
使用该指令跑total-text-mat（dataset/TotalText）下的数据集是没问题的。
总的来说就是：旧版数据集可以正常训练，但是新版本却遇到了问题。（仅仅修改了训练集的标签注释文件）
改用新数据集，即Trainset(TotalText_New)报如下错误
（在执行数据增强时，RandomCropFlip类中的call函数中ppi = Polygon(polygon.points).buffer(0)这一行代码ValueError: A linearring requires at least 4 coordinates）
![12](https://github.com/user-attachments/assets/18fde291-3182-4492-b4a1-2001382a2212)

**Comment by lightchaser0** [comment]
补充：是在epoch=0，第三次迭代时报错（epoch=0 : (20/105)）

**Comment by WudiJoey** [comment]
`ValueError: A linearring requires at least 4 coordinates` This is due to the fact that some polygons in the dataset annotation have fewer than 4 points. You should use `if len(x) < 4:   continue` to filter useless polygons in TotalText_New.py .

**Comment by lightchaser0** [comment]
> `ValueError: A linearring requires at least 4 coordinates` This is due to the fact that some polygons in the dataset annotation have fewer than 4 points. You should use `if len(x) < 4: continue` to filter useless polygons in TotalText_New.py .

Thank you very much, it works!

**Comment by WudiJoey** [comment]
您好，您的来信我已经收到，会尽快回复。
