### ISSUE TITLE
out of  memory

### ISSUE THREAD

**Issue by 1c123** [GXYM/TextBPN-Plus-Plus#7]
Hello, I am taking up a lot of memory in the process of running the test, what is the reason?

**Comment by 1c123** [comment]
Hello, it is the GPU memory. I trained and tested under python=3.6 and torch=1.10, but the test video memory exceeded 24G.

**Comment by GXYM** [comment]
> Hello, it is the GPU memory. I trained and tested under python=3.6 and torch=1.10, but the test video memory exceeded 24G.

Maybe， the input image size should be limitted. Art and MLT, I  suggest you use the 3090 with large GPU memory to testing because many images in these dadasets are very large.

**Comment by 123cjjjj** [comment]
> > Hello, it is the GPU memory. I trained and tested under python=3.6 and torch=1.10, but the test video memory exceeded 24G.
> 
> Maybe， the input image size should be limitted. Art and MLT, I suggest you use the 3090 with large GPU memory to testing because many images in these dadasets are very large.

您好，如果使用3090运行该项目的话，需要调整哪些参数啊？运行的结果与3080环境上相差有点大

**Comment by GXYM** [comment]
> 具体实践的是TextPMs，是不是需要在3090环境下调整一下参数？想请您指导下 | | cxh | | ***@***.*** | ---- Replied Message ---- | From | ***@***.***> | | Date | 4/13/2023 16:53 | | To | ***@***.***> | | Cc | ***@***.***> , ***@***.***> | | Subject | Re: [GXYM/TextBPN-Plus-Plus] out of memory (Issue #7) | Hello, it is the GPU memory. I trained and tested under python=3.6 and torch=1.10, but the test video memory exceeded 24G. Maybe， the input image size should be limitted. Art and MLT, I suggest you use the 3090 with large GPU memory to testing because many images in these dadasets are very large. 您好，如果使用3090运行该项目的话，需要调整哪些参数啊？运行的结果与3080环境上相差有点大 我们使用的就是3090和2080的环境，抱歉readme里写错了，一直没注意。你是运行测试，还是重新训练在测试，那个相差比较大？TextBPN++我们之前有过一次更新，修复了一些训练的bug，现在应该没有什么问题了呀。我们修改和测试的记录在这：https://github.com/GXYM/TextBPN-Plus-Plus/tree/main/output — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

TextPMs那个工程里的训练脚本不全，不能认为直接运行那个训练脚本就可以复现结果；训练过程参考论文，测试的话测试尺寸应该要和论文保持一致，阈值参数在论文提供的参数左右微调,应该就差不多了。
