### ISSUE TITLE
The results of running on the TD500 dataset are quite different from those given in the paper

### ISSUE THREAD

**Issue by HHeracles** [GXYM/TextBPN-Plus-Plus#8]
Thanks for your work, but when I replicated your algorithm on the TD500 dataset, I found a problem. We downloaded the dataset and the model you provided and ran the test instruction “CUDA_LAUNCH_BLOCKING=1 python3 eval_textBPN.py --net resnet50 --scale 1 --exp_name TD500 --checkepoch 107000 --test_size 640 960 --dis_threshold 0.35 --cls_threshold 0.9 --gpu 0”, and the performance data obtained was {"precision": 0.6811594202898551, "recall": 0.6460481099656358, "hmean": 0.6631393298059965, "AP": 0}, which was quite different from the data provided in the paper. How can I set it to reproduce the performance data you gave?

**Comment by GXYM** [comment]
> Thanks for your work, but when I replicated your algorithm on the TD500 dataset, I found a problem. We downloaded the dataset and the model you provided and ran the test instruction “CUDA_LAUNCH_BLOCKING=1 python3 eval_textBPN.py --net resnet50 --scale 1 --exp_name TD500 --checkepoch 107000 --test_size 640 960 --dis_threshold 0.35 --cls_threshold 0.9 --gpu 0”, and the performance data obtained was {"precision": 0.6811594202898551, "recall": 0.6460481099656358, "hmean": 0.6631393298059965, "AP": 0}, which was quite different from the data provided in the paper. How can I set it to reproduce the performance data you gave?

This is due to the high version of opencv.
